# Generated by Django 4.2.6 on 2023-10-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('room_type', models.CharField(max_length=100)),
                ('room_price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
