# Generated by Django 4.2.6 on 2023-11-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="booked_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="booked_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
