# Generated by Django 4.2.6 on 2023-11-02 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_room_booked_from_room_booked_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="booked_from",
        ),
        migrations.RemoveField(
            model_name="room",
            name="booked_to",
        ),
    ]
