# Generated by Django 4.2.6 on 2023-11-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True),
                ),
                ("password", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
