# Generated by Django 4.2.6 on 2023-10-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="checked_out",
        ),
        migrations.AddField(
            model_name="reservation",
            name="checked_out_at",
            field=models.DateTimeField(null=True),
        ),
    ]
