# Generated by Django 4.2.6 on 2023-11-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0002_remove_reservation_checked_out_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="checked_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="completed",
            field=models.CharField(max_length=100),
        ),
    ]
